config/routes.rb
require 'sidekiq/web'
# sessionの上書きをオフにする。(Ryoさんのslackをカンニングしました)
Sidekiq::Web.set :sessions, false

Rails.application.routes.draw do
  # development環境の際にletter_operner_webを使用できるように追加
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # mount Sidekiq::Web => '/sidekiq'と書くのと同じ様子
  mount Sidekiq::Web, at: '/sidekiq'
  root 'posts#index'

  # セッション管理のルーティングを以下に記載。
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # %iでシンボルの配列がリテラルでかける。
  resources :users, only: %i[new create show index]
  # shallowオプションでcommentsのedit,show,destroy,updateに/posts/:post_idが付かなくなる。
  resources :posts, shallow: true do
    resources :comments
    # /posts/searchのルーティングを作成する。(/posts/:id/searchとしたい場合は、memberを使う)
    get :search, on: :collection
  end
  # 今回はネストさせずにルーティングを設定(postsにネストさせてもできそう！)
  resources :likes, only: %i[create destroy]

  resources :relationships, only: %i[create destroy]

  # patchメソッドの「/activities/:id/read」のエンドポイントを作成する。
  resources :activities, only: [] do
    patch :read, on: :member
  end
  # 「マイページ系」の機能拡張を想定してnamespaceを使用する。(URL、ファイル構成ともにmypage配下になる)
  namespace :mypage do
    # アカウントはログインユーザーからみてアプリケーション上、１つしか存在しないので:idを生成しない「resource」を使用する。
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :bigint
#  user_id    :bigint
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#  index_comments_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (post_id => posts.id)
#  fk_rails_...  (user_id => users.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  # コメントを削除すると関連アクティティも削除する。
  # commnetsテーブルとactivitiesテーブルの関係は、1対多なのでhas_manyで関連付け。
  has_many :activity, as: :subject, dependent: :destroy

  # nullは不可および文字数を1000文字までに制限するバリデーションを追加’
  validates :body, presence: true, length: { maximum: 1000 }

  # after_create_commitは、after_commitのエイリアス
  # インスタンスがcreateされた後に以下を関数をコールバックする。
  after_create_commit :create_activities

  private

  def create_activities
    # インスタンスメソッド内のselfなので、commentインスタンスが入る。
    # action_typeにはenumで定義をした項目を入れる。
    Activity.create(subject: self, user: post.user, action_type: :commented_to_own_post)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: %i[create edit update destroy]

  def create
    # ログイン中のユーザーと関連をさせて、コメントのインスタンス作成する。(関連を使用する時は慣習的にnewでなく、buildを使う。)
    # user_idはcurrent_userを使って、post_idはURLからparams経由で登録をする。
    @comment = current_user.comments.build(comment_params)
    # @comment.save
    # コメントをされたユーザー(@comment.post.user)の通知設定フラグ(notification_comment)がtureであればメール送信をする。
    UserMailer.with(user_from: current_user, user_to: @comment.post.user, comment: @comment).comment_post.deliver_later if @comment.save && @comment.post.user.notification_comment?
  end

  def edit
    @comment = current_user.comments.find(params[:id])
  end

  def update
    @comment = current_user.comments.find(params[:id])
    @comment.update(comment_update_params)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
  end

  private

  def comment_params
    # mergeメソッドを使用することで、URLに含まれるpost_idをActionController::Parametersインスタンスを生成できる。
    # コンソールで右記を確認。<ActionController::Parameters {"body"=>"テスト", "post_id"=>"44"} permitted: true>
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end

  def comment_update_params
    # post_idはすでに保存されているため、merge不要。(外部キーはpermitにカラム記載不要！)
    params.require(:comment).permit(:body)
  end
end

app/views/comments/_comment.html.slim
/ JSを使用してDOM操作をする対象を判別するためにhtmlのid属性にcommentのidを入れておく。
div id="comment-#{comment.id}"
  / no-guttersとすることで各カラムの左右の余白が0になる。
  .row.no-gutters
    .col-2
      = image_tag comment.user.avatar.url, size: '40x40', class: 'rounded-circle'
    .col-9
      span.font-weight-bold.pr-1
        = comment.user.username
      = comment.body
    .col-1
      / 自分のコメントであれば、編集・削除アイコンを表示する。
      - if current_user&.own?(comment)
        = link_to comment_path(comment), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'}, remote: true do
          = icon 'far', 'trash-alt', class: 'fa-sm'
        = link_to edit_comment_path(comment), remote: true do
          = icon 'far', 'edit', class: 'fa-sm'
  / hrは水平線を引くためのタグ
  hr

app/views/comments/_comments.html.slim
/ render commentsは、「_comments.html.slim」をレンダリングしている訳ではない！！
/ commentsには@comentsが渡されているため、collectionオプションが使用されている。
/ 省略形でない形に変換して考えると以下となる。
/ - @comments.each do |comment|
/   = render partial: 'comment', locals: {comment: comment}
/ 上記よりローカル変数(comment)にインスタンス変数(@comment)を渡して、テンプレート(comments/_comment.heml.slim)をレンダリングする。  
.comments-box
  = render comments

app/views/comments/_form.html.slim
/ 新規登録の場合は、「posts/:post_id/comments」というURLを作成したいので、「model: [post, comment]」とする。(デフォルトで非同期通信なので、remote: trueは省略可能)
/ 非同期通信でのリクエストは、JS形式となるため「create.js.erb」or「update.js.erb」がコントローラー経由で呼ばれる。
= form_with model: [post, comment], class: 'd-flex mb-0 flex-nowrap justify-content-between', remote: true do |f|
  = f.text_field :body, class: 'form-control input-comment-body', placeholder: 'コメント'
  = f.submit '投稿', class: 'btn btn-primary btn-raised'

app/views/comments/_modal_form.html.slim
/ dom操作用にidを定義
.modal#comment-edit-modal
  .modal-dialog
    .modal-content
      .modal-header
        h5.modal-title コメント編集
        / 自分でモーダルを作成した時は、bootstrapの公式をみるとクラス名などわかりそう。
        / 以下は静的なモーダルを作成している。
        button.close aria-label="Close" data-dismiss="modal" type="button"
          / 公式だと「&times;」であった。(×印の文字参照らしい)
          span aria-hidden="true"  &times;
      .modal-body
        / _form.html.slimをレンダリングする。/commnet/idというactionを作成すれば良いため、postはnilとする。
        = render 'form', post: nil, comment: comment

app/views/comments/create.js.slim
/ 非同期処理の場合は、こちらでエラーの場合の表示制御を行う。
/ js.slimファイルでjsのコードを記載したい場合は、パイプを使う必要がある。(erbの場合はタグを書かないだけでOK)
- if @comment.errors.present?
  /エラーがある場合は、内容をalertメソッドで出力をする。
  / @comment.errors.full_messagesは配列形式でエラーメッセージが入っているため、join('\n')で連結&改行させる。
  | alert("#{@comment.errors.full_messages.join('\n')}");

/ なぜ「$(document).ready」でdomの読み込みを待つ必要がない？→操作対象のDOM自体は「posts/show.html.slim」で表示済みであるから！
-else
  / comments-boxクラスの先頭に_comment.html.slimの内容をレンダリングさせる！(難しい！！！)
  / またescape_javascript(エイリアスで「j」)メソッドでレンダリングの結果をJS用に変換？する。
  | $('.comments-box').prepend("#{j render('comments/comment', comment: @comment)}");
  / input-comment-bodyクラス(入力欄)の内容をブランクにする。
  | $('.input-comment-body').val('');

app/views/comments/destroy.js.slim
/ 削除対象のコメントIDをhtmlのID要素より削除をする。
| $('#comment-#{@comment.id}').remove()

app/views/comments/edit.js.slim
/ htmlメソッドでmodal-containerのID箇所(application.html.slim)にcomments/_modal_formを表示させるようにDOM操作
| $("#modal-container").html("#{j(render 'modal_form', comment: @comment)}");
/ _modal_form.html.slimをモーダル形式で表示をさせる。
| $("#comment-edit-modal").modal('show');

app/views/comments/update.js.slim
- if @comment.errors.present?
  | alert("#{@comment.errors.full_messages.join('\n')}");
- else
  / _comment.heml.slim(コメントの1つの部分)をhtmlメソッドでdomを書き換える。
  | $("#comment-#{@comment.id}").html("#{j render('comments/comment', comment: @comment)}");
  / _modal_form.html.slim(モーダルの中身部分)をmodalメソッドで閉じる。
  | $("#comment-edit-modal").modal('hide');