config/routes.rb
require 'sidekiq/web'
# sessionの上書きをオフにする。(Ryoさんのslackをカンニングしました)
Sidekiq::Web.set :sessions, false

Rails.application.routes.draw do
  # development環境の際にletter_operner_webを使用できるように追加
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # mount Sidekiq::Web => '/sidekiq'と書くのと同じ様子
  mount Sidekiq::Web, at: '/sidekiq'
  root 'posts#index'

  # セッション管理のルーティングを以下に記載。
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # %iでシンボルの配列がリテラルでかける。
  resources :users, only: %i[new create show index]
  # shallowオプションでcommentsのedit,show,destroy,updateに/posts/:post_idが付かなくなる。
  resources :posts, shallow: true do
    resources :comments
    # /posts/searchのルーティングを作成する。(/posts/:id/searchとしたい場合は、memberを使う)
    get :search, on: :collection
  end
  # 今回はネストさせずにルーティングを設定(postsにネストさせてもできそう！)
  resources :likes, only: %i[create destroy]

  resources :relationships, only: %i[create destroy]

  # patchメソッドの「/activities/:id/read」のエンドポイントを作成する。
  resources :activities, only: [] do
    patch :read, on: :member
  end
  # 「マイページ系」の機能拡張を想定してnamespaceを使用する。(URL、ファイル構成ともにmypage配下になる)
  namespace :mypage do
    # アカウントはログインユーザーからみてアプリケーション上、１つしか存在しないので:idを生成しない「resource」を使用する。
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                   :bigint           not null, primary key
#  avatar               :string(255)
#  crypted_password     :string(255)
#  email                :string(255)      not null
#  notification_comment :boolean          default(TRUE)
#  notification_follow  :boolean          default(TRUE)
#  notification_like    :boolean          default(TRUE)
#  salt                 :string(255)
#  username             :string(255)      not null
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#
class User < ApplicationRecord
  authenticates_with_sorcery!

  # 「アップロード画像用のカラム」と「アップローダークラス」を紐付け
  mount_uploader :avatar, AvatarUploader

  # 以下バリデーションを追加(回答も見ながら写経)
  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  # 「if: ->」と書き方は見慣れないが、->の右側がtureであればバリデーションが実行される？？
  # new_record?(新しいレコード)もしくはchanges[:crypted_password](パスワード更新時)にバリデーションが実行される？？
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  # 関連を定義。dependentオプションでuserが削除されたら、関連するpostも削除とする。
  has_many :posts, dependent: :destroy

  # 後から関連モデルを作成しても既存のモデルには関連の定義は自動では記載されないため注意する。
  has_many :comments, dependent: :destroy

  # postsモデルと同様に関連を定義する。
  has_many :likes, dependent: :destroy
  has_many :like_posts, through: :likes, source: :post

  # 【特定のユーザーがフォローをしているユーザーとの関係】
  # ■relationshipsテーブ(中間テーブル)との関連を定義
  # ①名前被りを防ぐため、active_をつけて、class_nameオプションでモデル指定。
  # ②「user_id」が外部キーではないため、foreign_keyオプションで外部キーを指定。
  # ③ユーザーを削除した時に中間テーブルの該当項目も削除したいため、dependent: :destroyオプションを指定。
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  # ■followedテーブル(usersテーブル)との関連を定義(active_relationships経緯)
  # 中間テーブルを介してfollowedモデルのUser(フォローされた側)を集めることを「following」と定義する。(source: :userとやりたくなるが、user_idと内部結合使用としてしまうためNG)
  has_many :following, through: :active_relationships, source: :followed

  # 【特定のユーザーがフォローされるユーザーとの関係】
  # ■relationshipsテーブル(中間テーブル)との関連を定義
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  # ■followerテーブル(usersテーブル)との関連を定義(passive_relationships経緯)
  has_many :followers, through: :passive_relationships, source: :follower
  # ユーザーが削除したら、関連のアクティビティを削除する。
  has_many :activities, dependent: :destroy

  # scopeでrecentメソッド()を定義する。
  # クラスメソッドと異なり常にActiveRecord::Relationオブジェクトを返すためメソッドチェーンを使える。(nilの場合は、allメソッドとなる)
  scope :recent, ->(count) { order(created_at: :desc).limit(count) }

  # 投稿が自身のものかを判別するためのメソッドを定義
  def own?(object)
    id == object.user_id
  end

  # ①self.like_postsでcurrent_userがlikeをしたpostをlikesテーブル経由で取得。
  # ②引数のpost(いいねをしたい投稿)を①に追加をする。
  def like(post)
    like_posts << post
  end

  # ①self.like_postsでcurrent_userがlikeをしたpostをlikesテーブル経由で取得。
  # ②引数のpost(いいねを解除したい投稿)を①から削除をする。
  def unlike(post)
    like_posts.destroy(post)
  end

  # ①self.like_postsでcurrent_userがlikeをしたpostをlikesテーブル経由で取得。
  # ②include?メソッドで引数のpostオブジェクトが①にあるかを確認。
  # ③②の結果によりtrue,falseを返す。
  def like?(post)
    like_posts.include?(post)
  end

  # ①self.followingでcurrent_userがフォローしたユーザーを取得。
  # ②引数のユーザーを①に追加
  def follow(other_user)
    following << other_user
  end

  # ①self.followingでcurrent_userがフォローしたユーザーを取得。
  # ②destroyメソッドをメソッドチェーンして、引数のユーザーを削除。
  def unfollow(other_user)
    following.destroy(other_user)
  end

  # ①self.followingでcurrent_userがフォローしたユーザーを取得。
  # ②include?メソッドをメソッドチェーンして、引数のユーザーが含まれているか確認。(フォローしているか確認できる)
  def following?(other_user)
    following.include?(other_user)
  end

  # ①「self.following_ids << self.id」でcurrent_userがフォローしているユーザーidにcurrent_userのユーザーidを追加する。
  # ②postテーブルで上記①のユーザーidの投稿をActiveRecord::Relationで返す。(自分と投稿とフォローしているユーザーの投稿を取得できる)
  def feed
    Post.where(user_id: following_ids << id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # Sorceryにより登録後のオートログインができる。
      auto_login(@user)
      # flash[:success]に「ユーザーを作成しました」をセットしてリダイレクトする。
      redirect_to login_path, success: 'ユーザーを作成しました'
    else
      flash.now[:danger] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all.page(params[:page]).order(created_at: :desc)
  end

  private

  # ストロングパラメーターを定義
  def user_params
    params.require(:user).permit(:email, :password, :password, :password_confirmation, :username)
  end
end

app/views/users/_follow.html.slim
/ フォローを追加したいため、以下手順でrelationshipsテーブルにレコード作成をする。
/ relationships_path(followed: user.id)でクエリパラメーターでフォロー対象のuser_idを渡しつつcreateアクションに飛ばす。
= link_to relationships_path(followed_id: user.id), class: 'btn btn-raised btn-outline-warning', method: :post, remote: true do
  | フォロー

app/views/users/_follow_area.html.slim
/ ログイン中かつ自分のユーザー表示でなければ
- if logged_in? && current_user.id != user.id
  / 非同期で処理処理するためidを用意
  div id="follow-area-#{user.id}"
    / ユーザーのフォロー有無を出し分けをする
    - if current_user.following?(user)
      = render 'users/unfollow', user: user
    -else
      = render 'users/follow', user: user

app/views/users/_unfollow.html.slim
/ フォローを解除したいため、以下手順でrelationshipsテーブルから該当のレコードを削除する。
/ ①current_user.active_relationshipsでログインユーザーがフォローしているレコードをrelationshipsより取得
/ ②find_by(followed_id: user.id)で①のレコードから今回フォローを外すのuserのレコードを指定
/ ③レコードの削除を非同期で実行したいため、deleteメソッドかつremote: trueオプションをしてする。
= link_to relationship_path(current_user.active_relationships.find_by(followed_id: user.id)), class: 'btn btn-warning btn-raised', method: :delete, remote: true do
  | アンフォロー

app/views/users/_user.html.slim
.user.mb-3.d-flex.justify-content-between
  / ユーザーの写真、ユーザーの名前をユーザー詳細ページへのリンクとする。
  = link_to user_path(user) do
    = image_tag user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
    = user.username
  = render 'users/follow_area', user: user
hr

app/views/users/index.html.slim
/ 投稿一覧で作成したユーザー一覧(右側の部分)の件数制限なし版をユーザー一覧画面として作成する。
.container
  .row
    .col-md-6.col-12.offset-md-3.mb-3
      .card
        .card-body
          = render @users
    .col-md-6.col-12.offset-md-3
      / ページネーションをつける
      = paginate @users

app/views/users/new.html.slim
/ viewについては解答を写経(bootstrap-material-design公式サイトでどんなデザインになるかは確認)
/ 以下の2つのクラスはapplication.scssに定義(ログインフォームを真ん中におくため)
.login-register-form
  .login-register-form-inner
    / カードかつmargin-bottomを1rem(ルート要素の等倍)のデザイン。
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true do |f|
        / エラーメッセージ部分はテンプレートで呼び出し、ローカル変数にオブジェクトを渡す。(objectというローカル変数名で@userオブジェクトを渡している。)
        = render 'shared/error_messages', object: @user
        / 公式だと「bmd-label-floating」はラベル名のアニメーションが出るみたいだが、「.bmd-label-static」と同様になっているのはなぜ？？
        .form-group
          = f.label :username, class: 'bmd-label-floating'
          = f.text_field :username, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'

        = f.submit '登録', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちですか
        = link_to 'ログインする', login_path

app/views/users/show.html.slim
/ ユーザー詳細ページを用意する。
.container
  .row
    .col-md-10.offset-md-1
      .card
        .card-body
          / 未ログイン時にエラーが出ないようにぼっち演算子を使用
          -if current_user&.id == @user.id
            .text-center.mb-3
              = link_to 'プロフィール編集', edit_mypage_account_path, class: 'btn btn-raised btn-warning'
          .text-center.mb-3
            = image_tag @user.avatar.url, size: '100×100', class: 'rounded-circle mr-1'
          .profile.text-center.mb-3
            = @user.username
          .text-center
            = render 'follow_area', user: @user
          / hrタグで水平線を引く
          hr
          .row
            / 自分の登録を全て表示する。
            / collectionオプションを使って部分テンプレートの呼び出しを行う。(eachで展開するよりもパフォーマンスも良いらしい)
            /　asオプションで任意の変数名の指定も可能
            /　テンプレートファイル名と変数名が異なるため、「render @user.posts」までの省略はできない。
            = render partial: 'posts/thumbnail_post', collection: @user.posts, as: "post"