config/routes.rb
require 'sidekiq/web'
# sessionの上書きをオフにする。(Ryoさんのslackをカンニングしました)
Sidekiq::Web.set :sessions, false

Rails.application.routes.draw do
  # development環境の際にletter_operner_webを使用できるように追加
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # mount Sidekiq::Web => '/sidekiq'と書くのと同じ様子
  mount Sidekiq::Web, at: '/sidekiq'
  root 'posts#index'

  # セッション管理のルーティングを以下に記載。
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # %iでシンボルの配列がリテラルでかける。
  resources :users, only: %i[new create show index]
  # shallowオプションでcommentsのedit,show,destroy,updateに/posts/:post_idが付かなくなる。
  resources :posts, shallow: true do
    resources :comments
    # /posts/searchのルーティングを作成する。(/posts/:id/searchとしたい場合は、memberを使う)
    get :search, on: :collection
  end
  # 今回はネストさせずにルーティングを設定(postsにネストさせてもできそう！)
  resources :likes, only: %i[create destroy]

  resources :relationships, only: %i[create destroy]

  # patchメソッドの「/activities/:id/read」のエンドポイントを作成する。
  resources :activities, only: [] do
    patch :read, on: :member
  end
  # 「マイページ系」の機能拡張を想定してnamespaceを使用する。(URL、ファイル構成ともにmypage配下になる)
  namespace :mypage do
    # アカウントはログインユーザーからみてアプリケーション上、１つしか存在しないので:idを生成しない「resource」を使用する。
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/views/shared/_before_login_header.html.slim
/ ログイン前の共通ヘッダー
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'ポスト一覧', posts_path, class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_commented_to_own_post.html.slim
/ 自分宛のコメントがある場合は、以下を表示する。
/ 「/activities/:id/read」へのリンク(既読判定のメソッド)を作り、cssで既読有無によって背景を変更する。
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  / activity.user.avatar.urlだと上手く取得できない。
  / ポリモーフィックの場合は、activity.subjectで対象のオブジェクトを取得する必要がある。
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  / aタグの中にaタグを使いたい時は、objectタグを使う(ただ別タブでリンクしないと上手くリンクされない！！)
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  object
    / activity.subjectでコメントのインスタンスを取得して、関連を使って投稿を取得する。
    = link_to '投稿', post_path(activity.subject.post)
  | に
  object
    / anchorをつけるとURLに「#comment-31」という形式アンカーリンクを生成できる。
    = link_to 'コメント', post_path(activity.subject.post, anchor: "comment-#{activity.subject.id}")
  | しました
  .ml-auto
    / ここではコメントのインスタンスではなく、アクティビティの作成時間を表示する。
    / lメソッドを使用して日本式の時刻表示にする。
    = l activity.created_at, format: :short

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  / 「error_messages.alert.alert-danger」はbootstrapで使用しているID？？(JSを使っている？？)
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
/ flashのキー(message_type)とバリュー(message)を取り出す
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_followed_me.html.slim
/ 自分宛のフォローがある場合は、以下を表示する。
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  / ここでのactivity.subjectはRelationshipインスタンスなので、followerでフォローしたuserインスタンスを取得する。
  = image_tag activity.subject.follower.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.follower.username, user_path(activity.subject.follower)
  | があなたをフォローしました
  .ml-auto
    = l activity.created_at, format: :short

app/views/shared/_header.html.slim
/ ログインできた場合の共通ヘッダー
/ 画面が小さくなると右側にトグルボタンが出現する。(BMDの公式にコードの記載もあり)
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    / 検索フォームをレンダリング
    = render 'posts/search_form', search_form: @search_form
    ul.navbar-nav.mt-2.mt-lg-0
      / Font Awesomeのアイコンを使用している。
      li.nav-item
        / link_toメソッドをブロックで書くことで、アイコンもリンクにすることができる。
        = link_to new_post_path, class: 'nav-link' do
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        .dropdown
          / slimの場合は、idとクラスは連続で記述できる。
          a#dropdownMenuButton.nav-link href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
            = icon 'far', 'heart', class: 'fa-lg'
            = render 'shared/unread_badge'
          /　aria-labelledbyにハートアイコン部分のIDを指定することで、ドロップダウンの項目にすることができる様子。(正直bootstrapは理解が怪しい...)
          #header-activities.dropdown-menu.dropdown-menu-right aria-labelledby="dropdownMenuButton"
            = render 'shared/header_activities'

      li.nav-item
        / ヘッダーのアイコンを自分の詳細ページへのリンクとする。
        = link_to user_path(current_user), class: 'nav-link' do
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_activities.html.slim
- if current_user.activities.present?
  / スコープを使って表示件数を絞る
  - current_user.activities.recent(10).each do |activity|
    / enumの確認メソッドを使ってビューファイルの出しわけを行う。
    = render "shared/#{activity.action_type}", activity: activity
  / 10件以上ある場合はリンクを表示させる。
  - if current_user.activities.count > 10
    = link_to '全てみる', mypage_activities_path,  class: 'dropdown-item justify-content-center'
- else
  .dropdown-item
    | お知らせはありません

app/views/shared/_liked_to_own_post.html.slim
/ 自分宛のいいねがある場合は、以下を表示する。
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do
  / ここでのactivity.subjectはlikeインスタンス
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  object
    = link_to '投稿', post_path(activity.subject.post)
  | にいいねしました
  .ml-auto
    = l activity.created_at, format: :short

app/views/shared/_modal.html.slim
/ comments/edit.js.slimよりモダール表示させるためIDのみ定義
#modal-container

app/views/shared/_unread_badge.html.slim
/ 「current_user.activities.unread」でログインユーザーがreadがfalseのインスタンスを取得できる。(enumの検索メソッド)
- if current_user.activities.unread.count > 0
  / 未読の数字を表示
  span.badge.badge-warning.navbar-badge.position-absolute style='top: 0; right:0;'
    = current_user.activities.unread.count