config/routes.rb
require 'sidekiq/web'
# sessionの上書きをオフにする。(Ryoさんのslackをカンニングしました)
Sidekiq::Web.set :sessions, false

Rails.application.routes.draw do
  # development環境の際にletter_operner_webを使用できるように追加
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  # mount Sidekiq::Web => '/sidekiq'と書くのと同じ様子
  mount Sidekiq::Web, at: '/sidekiq'
  root 'posts#index'

  # セッション管理のルーティングを以下に記載。
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  # %iでシンボルの配列がリテラルでかける。
  resources :users, only: %i[new create show index]
  # shallowオプションでcommentsのedit,show,destroy,updateに/posts/:post_idが付かなくなる。
  resources :posts, shallow: true do
    resources :comments
    # /posts/searchのルーティングを作成する。(/posts/:id/searchとしたい場合は、memberを使う)
    get :search, on: :collection
  end
  # 今回はネストさせずにルーティングを設定(postsにネストさせてもできそう！)
  resources :likes, only: %i[create destroy]

  resources :relationships, only: %i[create destroy]

  # patchメソッドの「/activities/:id/read」のエンドポイントを作成する。
  resources :activities, only: [] do
    patch :read, on: :member
  end
  # 「マイページ系」の機能拡張を想定してnamespaceを使用する。(URL、ファイル構成ともにmypage配下になる)
  namespace :mypage do
    # アカウントはログインユーザーからみてアプリケーション上、１つしか存在しないので:idを生成しない「resource」を使用する。
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  images     :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  # reference型で定義すると以下の関連も自動で定義される。
  belongs_to :user
  # 「アップロード画像用のカラム」と「アップローダークラス」を紐づける為に以下を記載。(複数の画像を扱うために)mount_uploader「s」)
  mount_uploaders :images, PostImageUploader
  # imagesはstring型で定義をしたため、JSON型で配列を保存するために定義。(mysqlを使用しているので、そもそもJSON型で定義しても良かったかも？？)
  serialize :images, JSON
  # バリデーションを追加
  validates :images, presence: true
  validates :body, presence: true, length: { maximum: 1000 }

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # likesテーブルを通してusersテーブルの情報も取得できるようにするために以下を定義
  # アソシエーション名をテーブル名と変更しているため、sourceモデル名(単数形！)を記載する。
  has_many :like_users, through: :likes, source: :user

  # 検索クエリのスコープを以下に定義
  scope :body_contain, ->(word) { where('body LIKE ?', "%#{word}%") }
  # commentsテーブルのcomment.bodyカラムを検索したいため、内部結合をする。またbodyカラムは名前が被るため、「comments.」としてテーブル特定をする。
  scope :comment_body_contain, ->(word) { joins(:comments).where('comments.body LIKE ?', "%#{word}%") }
  scope :username_contain, ->(word) { joins(:user).where('username LIKE ?', "%#{word}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # 「require_login」はsorceryにより使用可能。
  before_action :require_login, only: %i[new create edit update destroy]

  def index
    # 「複数のUserが投稿したPostを全件取得」かつ「誰が投稿したかアソシエーションを使用して表示」するとN+1問題(usersテーブルに1回+postsテーブルにN回アクセスのSQLが発生する問題)が発生する。
    # そのためincludesメソッドを使用して、「postsの全内容取得」と「関連するuserの全件取得」をしておく。(preloadを使用してもいいはず！)
    # params[:page]で表示するページ番号を渡しており、pageメソッドで渡されたページ番号の範囲のデータを取得している。
    # @posts = Post.all.includes(:user).page(params[:page]).order(created_at: :desc)

    # ログインをしている場合は、自分の投稿とフォローしたユーザーの投稿のみの表示とするため、if文で分岐。
    @posts = if current_user
               current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
             else
               Post.all.includes(:user).page(params[:page]).order(created_at: :desc)
             end
    # 最近作成のユーザー5件を表示するため、userインスタンスを作成。
    @users = User.recent(5)
  end

  def new
    @post = Post.new
  end

  def create
    # current_userに関連させてpostインスタンスを作成する。
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def edit
    # current_user.postsとすることで「user_idがcurrent_userの同一id（自分の投稿）」のpostからfindできる。
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, success: '投稿を更新しました'
    else
      flash.now[:danger] = '投稿の更新に失敗しました'
      render :edit
    end
  end

  def show
    # 他のユーザーの投稿の詳細ページも見たいので、current_user.postsとはしない。
    @post = Post.find(params[:id])
    # postの詳細画面にコメントを非同期で表示させるために以下を記載。
    # どのユーザーのコメントかの情報も表示するのにN+1問題を避けるためincludesでuser情報も取得。
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    # コメントにとってpostのshowアクションが新規登録画面となるのでコメントインスタンスを作成。
    @comment = Comment.new
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    # 削除が失敗したら例外をだす。
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました'
  end

  def search
    # ①@search_form(検索値)をレシーバとしてsearchメソッドを実行する。
    # ②N+1問題を解消させるためにincludes(:user)をメソッドチェーン
    # ページネーションのためにpage(params[:page])をさらにメソッドチェーン
    @posts = @search_form.search.includes(:user).page(params[:page])
  end

  private

  # 画像が単数の場合は:imageで良いが、複数の場合はimages: []とする。
  def post_params
    params.require(:post).permit(:body, images: [])
  end
end

app/views/posts/_form.html.slim
= form_with model: post, local: true do |f|
  = render 'shared/error_messages', object: post
  .form-group
    = f.label :images
    / 複数画像を扱う場合は、multiple: trueとする。
    = f.file_field :images, multiple: true, class: 'form-control'
    / アップロード済みの画像を全て表示(public以下に置くファイルはブラウザに送信されるので、配列を展開してimage.urlでファイルURLを取得して表示できる)
    - post.images.each do |image|
      = image_tag image.url, size: '100x100', class: 'image-thumbnail'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  = f.submit class: 'btn btn-primary btn-raised'

app/views/posts/_like.html.slim
/ likeはルーティングでネストをさせていないため、URLからpost_idを取得することができない。
/ なので(post_id: post.id)でクエリパラメーターとしてpost_idを渡す。
/ 生成されるリンクのURLは「href="/likes?post_id=43"」のような形式になる。
= link_to likes_path(post_id: post.id), method: :post, remote:true do
  = icon 'far', 'heart', class: 'fa-lg'

app/views/posts/_like_area.html.slim
/ 非同期でdom操作を行うためidを設定
div id="like_area-#{post.id}"
  / 対象の投稿にいいねをしてる場合は、_unlikeをレンダリング
  -if current_user.like?(post)
    = render 'unlike', post: post
  / 対象の投稿にいいねしていない場合は、_likeをレンダリング
  - else
    = render 'like', post: post

app/views/posts/_post.html.slim
.card.mb-5.post
  .card-header
    .d-flex.align-items-center
      = image_tag post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
      = post.user.username
      / ぼっち演算子(&.)を使用することでcurrent_userがnilの場合でもエラーが出ないようにしている。
      - if current_user&.own?(post)
        .ml-auto
          / 「method: :delete」は実はrails-ujsを使用しているらしい。
          = link_to post_path(post), class: 'mr-3', method: :delete, data: { confirm: '本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) do
            = icon 'far', 'edit', class: 'fa-lg'
      / current_userがnilでない(ログインしている)かつ自分の投稿でない場合はlike_area(likeボタン)を表示させる。
      - if current_user && !current_user.own?(post)
        / ml-autoでMargin Leftとして右側に配置する。
        .ml-auto
          / postインスタンスを渡して_like_areaをレンダリング
          = render 'like_area', post: post

  = link_to post_path(post) do
    / swiperのcssの当て方は公式のコードを見ながらやると良さそう。
    .swiper-container
      .swiper-wrapper
        - post.images.each do |image|
          .swiper-slide
            = image_tag image.url, class: 'card-img-top'
      .swiper-pagination
  .card-body
    .card-text
      = post.body

app/views/posts/_search_form.html.slim
/ ①modelオプションにSearchPostsFromクラスのインスタンスを設定
/ ②urlオプションに/posts/searchのアクションを生成するためのprefixを指定
/ ③scopeオプションに:qを指定する。
/ ④methodオプションにgetを指定してget通信とする。
= form_with model: search_form, url: search_posts_path, scope: :q, class: 'form-inline my-2 my-lg-0 mr-auto', method: :get, local: true do |f|
  / text_fieldとの違いは、入力欄の右端にクリアボタンが設定される。
  = f.search_field :post_body, class: 'form-control mr-sm-2', placeholder: '本文'
  = f.search_field :comment_body, class: 'form-control mr-sm-2', placeholder: 'コメント'
  = f.search_field :username, class: 'form-control mr-sm-2', placeholder: 'ユーザー名'
  = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/posts/_thumbnail_post.html.slim
/ 画面がPCサイズの場合は、親要素の12分の4の列幅で表示
/ マージンボトムは3rem(remとはhtml要素のfont-sizeを1remと定義するサイズ定義。bootstrapのデフォルトは、16pxらしい)
.col-md-4.mb-3
  = link_to post_path(post), class: 'thumbs' do
    / 「postインスタン.images.first.url」でPostImageUploaderクラスのメソッドを使って、1枚目の画像ファイルのURLを取得する。
    = image_tag post.images.first.url

app/views/posts/_unlike.html.slim
/ ①current_user.likesでcurrent_userに関連するデータをlikesテーブルから複数件取得。
/ ②find_by(post_id: post.id)で①の中から対象投稿のレコードを抽出。
/ ③上記より対象のlikeオブジェクトが戻り値になる。
/ ④生成されるリンクのURLは、「href="/likes/:id"」でHTTPメソッドはdeleteとなる。
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, remote: true do
  = icon 'fa', 'heart', class: 'fa-lg'

app/views/posts/edit.html.slim
.container
  .row
    .col-md-6.col-12.offset-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/index.html.slim
.container
  .row
    / グリッドシステムを使っている。(768px以上の場合は、12分割の8対2に分けている)
    .col-md-8.col-12
      / @postsがnilの場合は、「投稿がありません」を表示
      - if @posts.present?
        = render @posts
      - else
        .text-center.font-weight-bold
          | 投稿がありません
      / paginateメソッドで現在のページ数、他ページへのリンクを作成(このメソッド凄い！)
      = paginate @posts
    .col-md-4.col-12
      - if logged_in?
        .profile-box.mb-3
          = image_tag current_user.avatar.url , size: '50x50', class: 'rounded-circle mr-1'
          = current_user.username
      .users-box
        .card
          .card-header
            | ユーザー
          .card-body
            / 以下の省略形で記載
            / <% @users.each do |user| %>
            / <%= render partial: 'user', locals: {user: user} %>
            / <% end %>
            / users/_user.html.slimをレンダリング？(別ディレクトリでもディレクト名と同じ場合は可能？？)
            = render @users
          .card-footer
            = link_to 'すべて見る', users_path

app/views/posts/new.html.slim
.container
  .row
    .col-md-6.col-12.offset-md-3
      .card
        .card-body
          = render 'form', post: @post

app/views/posts/search.html.slim
/ 検索結果画面を作成
.container
  .row
    .col-md-8.col-12.offset-md-2
      h2.text-center
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            = image_tag image.url
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.username
        - if current_user&.own?(@post)
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post) do
              = icon 'far', 'edit', class: 'fa-lg'
        / current_userがnilでない(ログインしている)かつ自分の投稿でない場合はlike_area(likeボタン)を表示させる。
        -if current_user && !current_user.own?(@post)
          .ml-auto
            = render 'like_area', post: @post
    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle'
        .col-10
          / simple_formatだと改行タグも認識される。
          = simple_format(@post.body)
      hr
      / コメント一覧
      / ローカル変数(comments)にインスタンス変数(@comments)を渡して、テンプレート(comments/_comments.heml.slim)をレンダリングする。  
      = render 'comments/comments', comments: @comments
    / ログインユーザーのみに表示されるようにする。(sorceryによりlogged_in?メソッドが使用可能)
    - if logged_in?
      hr.m-0
      .post-comment.p-3
        / ローカル変数(post、comments)にインスタンス変数(@post、@comments)をそれぞれ渡して、テンプレート(comments/_form.heml.slim)をレンダリングする。  
        = render 'comments/form', post: @post, comment: @comment